# Documentation: https://github.com/roots/trellis#wordpress-sites
wordpress_sites:
  samfujera.cz:
    site_hosts:
      - samfujera.dev
    local_path: ../site # path targeting local Bedrock site directory (relative to Ansible root)
    repo: git@github.com:pavelsuba/samfujera.git
    site_install: true
    site_title: Sam Fujera
    admin_user: admin
    admin_password: admin
    admin_email: pavelsuba@live.com
    multisite:
      enabled: false
      subdomains: false
    ssl:
      enabled: false
    cache:
      enabled: false
      duration: 30s
    system_cron: true
    env:
      wp_home: http://samfujera.dev
      wp_siteurl: http://samfujera.dev/wp
      wp_env: development
      db_name: example_dev
      db_user: example_dbuser
      db_password: example_dbpassword