<?php
//* Start the engine
include_once( get_template_directory() . '/lib/init.php' );

//* Set Localization (do not remove)
load_child_theme_textdomain( 'samfujera', apply_filters( 'child_theme_textdomain', get_stylesheet_directory() . '/languages', 'samfujera' ) );

//* Child theme (do not remove)
define( 'CHILD_THEME_NAME', __( 'Sam Fujera Theme', 'samfujera' ) );
define( 'CHILD_THEME_URL', 'http://samfujera.cz/' );
define( 'CHILD_THEME_VERSION', '0.0.1' );

//* Enqueue Google Fonts
add_action( 'wp_enqueue_scripts', 'samfujera_google_fonts' );
function samfujera_google_fonts() {

	wp_enqueue_style( 'google-fonts-muli', '//fonts.googleapis.com/css?family=Muli|Cantarell', array(), CHILD_THEME_VERSION );
}

//* Add HTML5 markup structure
add_theme_support( 'html5', array( 'search-form', 'comment-form', 'comment-list' ) );

//* Add Accessibility support
add_theme_support( 'genesis-accessibility', array( 'headings', 'drop-down-menu',  'search-form', 'skip-links', 'rems' ) );

//* Add viewport meta tag for mobile browsers
add_theme_support( 'genesis-responsive-viewport' );

//* Add support for custom background
add_theme_support( 'custom-background' );

//* Add support for 3-column footer widgets
add_theme_support( 'genesis-footer-widgets', 3 );

add_theme_support( 'genesis-connect-woocommerce' );

//* Remove the post info function
remove_action( 'genesis_before_post_content', 'genesis_post_info' );

//* BEGIN Add custom favicons generated by favicon-generator.org
add_filter( 'genesis_pre_load_favicon', 'samfujera_pre_load_favicon' );

function samfujera_pre_load_favicon() {
 return get_stylesheet_directory_uri() . '/images/favicon/favicon.ico';
}

remove_action( 'wp_head', 'genesis_load_favicon' );
add_action( 'wp_head', 'samfujera_load_favicons' );

function samfujera_load_favicons() {
 $favicon_path = get_stylesheet_directory_uri() . '/images/favicon';
 ?>
 <link rel="apple-touch-icon" sizes="57x57" href="<?php echo $favicon_path; ?>/apple-touch-icon-57x57.png">
 <link rel="apple-touch-icon" sizes="60x60" href="<?php echo $favicon_path; ?>/apple-touch-icon-60x60.png">
 <link rel="apple-touch-icon" sizes="72x72" href="<?php echo $favicon_path; ?>/apple-touch-icon-72x72.png">
 <link rel="apple-touch-icon" sizes="76x76" href="<?php echo $favicon_path; ?>/apple-touch-icon-76x76.png">
 <link rel="apple-touch-icon" sizes="114x114" href="<?php echo $favicon_path; ?>/apple-touch-icon-114x114.png">
 <link rel="apple-touch-icon" sizes="120x120" href="<?php echo $favicon_path; ?>/apple-touch-icon-120x120.png">
 <link rel="apple-touch-icon" sizes="144x144" href="<?php echo $favicon_path; ?>/apple-touch-icon-144x144.png">
 <link rel="apple-touch-icon" sizes="152x152" href="<?php echo $favicon_path; ?>/apple-touch-icon-152x152.png">
 <link rel="apple-touch-icon" sizes="180x180" href="<?php echo $favicon_path; ?>/apple-touch-icon-180x180.png">
 <link rel="icon" type="image/png" href="<?php echo $favicon_path; ?>/favicon-32x32.png" sizes="32x32">
 <link rel="icon" type="image/png" href="<?php echo $favicon_path; ?>/android-chrome-192x192.png" sizes="192x192">
 <link rel="icon" type="image/png" href="<?php echo $favicon_path; ?>/favicon-96x96.png" sizes="96x96">
 <link rel="icon" type="image/png" href="<?php echo $favicon_path; ?>/favicon-16x16.png" sizes="16x16">
 <link rel="manifest" href="<?php echo $favicon_path; ?>/manifest.json">
 <link rel="shortcut icon" href="<?php echo $favicon_path; ?>/favicon.ico">
 <meta name="msapplication-TileColor" content="#52d2e0">
 <meta name="msapplication-TileImage" content="<?php echo $favicon_path; ?>/mstile-144x144.png">
 <meta name="msapplication-config" content="<?php echo $favicon_path; ?>/browserconfig.xml">
 <meta name="theme-color" content="#ffffff">
 
<? }

//* END Add custom favicons generated by favicon-generator.org

//* Register footer navigation menu

function samfujera_register_footer_nav() {
	register_nav_menu( 'footer-nav' ,__( 'Footer Navigation Menu' ));
}
add_action( 'init', 'samfujera_register_footer_nav' );

//* Add custom footer with footer navigation menu
remove_action( 'genesis_footer', 'genesis_do_footer' );
add_action( 'genesis_footer', 'samfujera_do_footer' );
function samfujera_do_footer() {
	wp_nav_menu( array( 'theme_location' => 'footer-nav', 'container_class' => 'samfujera-footer-nav' ) );
	$acorn_img = get_stylesheet_directory_uri() . '/images/sam-acorn.png';
	?>
	<div id="copyright">&copy; Copyright <?php echo date('Y'); ?> <a href="<?php bloginfo('url'); ?>"><?php bloginfo('name'); ?></a> &middot; 
	<strong>Veřejné šíření informací na této stránce je možné jen za písemného souhlasu Sama Fujery a s odvoláním jmenovitě na autora.</strong></div>
	<div id="acorn-footer-img"><img src="<?php echo $acorn_img; ?>"></img></div>
	<?php	
}

//* Enable the superfish script
add_filter( 'genesis_superfish_enabled', '__return_true' );

//* Reposition the secondary navigation menu
remove_action( 'genesis_after_header', 'genesis_do_subnav' );
add_action( 'genesis_before_header', 'genesis_do_subnav' );

//* Add search form to navigation menu
add_filter( 'wp_nav_menu_items', 'samfujera_menu_searchform', 10, 2 );
function samfujera_menu_searchform( $menu, $args ) {
	//* Change 'primary' to 'secondary' to add extras to the secondary navigation menu
	if ( 'primary' !== $args->theme_location )
		return $menu;
	ob_start();
	get_search_form();
	$search = ob_get_clean();
	$menu  .= '<li class="right search">' . $search . '</li>';
	return $menu;
}

/** Register widget areas */
genesis_register_sidebar( array(
	'id'          => 'home-left',
	'name'        => __( 'Home Left', 'samfujera' ),
	'description' => __( 'This is the home left section.', 'samfujera' ),
) );
genesis_register_sidebar( array(
	'id'          => 'home-middle',
	'name'        => __( 'Home Middle', 'samfujera' ),
	'description' => __( 'This is the home middle section.', 'samfujera' ),
) );
genesis_register_sidebar( array(
	'id'          => 'home-right',
	'name'        => __( 'Home Right', 'samfujera' ),
	'description' => __( 'This is the home right section.', 'samfujera' ),
) );

add_action('genesis_after_comment_form', 'samfujera_after_comments');

//* Change the default venue slug to in Event Espresso 4
add_filter( 'FHEE__EE_Register_CPTs__register_CPT__rewrite', 'samfujera_custom_venues_slug', 10, 2 );
function samfujera_custom_venues_slug( $slug, $post_type ) {
  if ( $post_type == 'espresso_venues' ) {
    $custom_slug = array( 'slug' => 'mista-konani' );
    return $custom_slug;
  }
  return $slug;
}
//* Change the default event category slug to in Event Espresso 4
add_filter( 'FHEE__EE_Register_CPTs__get_taxonomies__taxonomies', 'samfujera_custom_event_category_slug');
	function samfujera_custom_event_category_slug( $thearray ) {

		if ( !empty($thearray['espresso_event_categories']) ) {
			$thearray['espresso_event_categories']['args']['rewrite']['slug'] = 'kategorie-akci';
			return $thearray;
		}
		return $thearray;
	}

define( 'EE_THEME_FUNCTIONS_LOADED', TRUE );
 
/**
 * 	espresso_pagination
 *
 *  @access 	public
 *  @return 	void
 */
function espresso_pagination() {
	global $wp_query;
	$big = 999999999; // need an unlikely integer
	$pagination = paginate_links( array(
		'base' => str_replace( $big, '%#%', esc_url( get_pagenum_link( $big ) ) ),
		'format' => '?paged=%#%',
		'current' => max( 1, get_query_var('paged') ),
		'total' => $wp_query->max_num_pages,
		'show_all'     => TRUE,
		'end_size'     => 10,
		'mid_size'     => 6,
		'prev_next'    => TRUE,
		'prev_text'    => __( '&lsaquo;&lsaquo; Previous Page', 'samfujera' ),
		'next_text'    => __( 'Next Page &rsaquo;&rsaquo;', 'samfujera' ),
		'type'         => 'list',
		'add_args'     => FALSE,
		'add_fragment' => ''
	));
	echo ! empty( $pagination ) ? '<div class="archive-pagination pagination"><ul>' . $pagination . '</ul></div>' : '';
}